### ISSUE TITLE
Carthage update build fails for watchOS target

### ISSUE THREAD

**Issue by diegomedina248** [kylef/WebLinking.swift#4]
Hi,

When trying to build the 1.0 release for watchOS with carthage, with the following command:
`carthage update WebLinking.swift --platform watchOS`

i get the following error:

`The following build commands failed:
    CompileSwift normal armv7k /Users/medina/Documents/Opera/Carthage/Checkouts/WebLinking.swift/WebLinkingTests/WebLinkingTests.swift
    CompileSwiftSources normal armv7k com.apple.xcode.tools.swift.compiler
(2 failures)
/Users/medina/Documents/Opera/Carthage/Checkouts/WebLinking.swift/WebLinking/WebLinking.swift:167:16: warning: curried function declaration syntax will be removed in a future version of Swift; use a single parameter list
/Users/medina/Documents/Opera/Carthage/Checkouts/WebLinking.swift/WebLinking/WebLinking.swift:174:11: warning: curried function declaration syntax will be removed in a future version of Swift; use a single parameter list
/Users/medina/Documents/Opera/Carthage/Checkouts/WebLinking.swift/WebLinking/WebLinking.swift:197:10: warning: curried function declaration syntax will be removed in a future version of Swift; use a single parameter list
/Users/medina/Documents/Opera/Carthage/Checkouts/WebLinking.swift/WebLinkingTests/WebLinkingTests.swift:10:8: error: no such module 'XCTest'
A shell task failed with exit code 65:
** BUILD FAILED **`

I have the following in my Cartfile:
`github "kylef/WebLinking.swift" ~> 1.0`

It builds for the rest of the platforms though.
Thanks!

**Comment by diegomedina248** [comment]
Hey, i believe the problem is that you cannot unit test for watchOS. In fact, if you try to build for watchOS you will see it does not compile due it cannot find XCTest.
Not compiling the test for the watchOS target will do the trick. I do not know if it is possible as is, or if it would be necessary to create a separate test target for that. Let me know if you want me to do it, or if there is another simpler solution.

**Comment by kylef** [comment]
This has been fixed in WebLinking 1.0.1.
