### ISSUE TITLE
Tag new release and update podspec for Swift 3.0 support changes

### ISSUE THREAD

**Issue by robmaceachern** [kylef/WebLinking.swift#8]
Thank you very much for the helpful library.

Swift 3 support was added as part of https://github.com/kylef/WebLinking.swift/commit/fddbacc30deab8afe12ce1d3b78bd27c593a0c29 but there hasn't been a new release of WebLinking to pick up those changes.

**Comment by kylef** [comment]
This was tagged a while ago, didn't realise there was this issue asking. https://github.com/kylef/WebLinking.swift/releases/tag/2.0.0
